ns-3: UanTest Class Reference
UanTest Class Reference
UAN Models » uan module tests | Test suites
Uan Test.
Public Member Functions
UanTest ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
Ptr< UanNetDevice > CreateNode (Vector pos, Ptr< UanChannel > chan)
Create node function.
uint32_t DoOnePhyTest (Time t1, Time t2, uint32_t r1, uint32_t r2, Ptr< UanPropModel > prop, uint16_t mode1=0, uint16_t mode2=0)
Do one Phy test function.
bool DoPhyTests ()
Phy test function.
bool RxPacket (Ptr< NetDevice > dev, Ptr< const Packet > pkt, uint16_t mode, const Address &sender)
Receive packet function.
void SendOnePacket (Ptr< UanNetDevice > dev, uint16_t mode)
Send one packet function.
Private Attributes
uint32_t m_bytesRx
byes received
ObjectFactory m_phyFac
Phy.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Uan Test.
Definition at line 43 of file uan-test.cc.
Constructor & Destructor Documentation
UanTest()
UanTest::UanTest ()
Definition at line 95 of file uan-test.cc.
Member Function Documentation
CreateNode()
Ptr< UanNetDevice > UanTest::CreateNode (Vector pos, Ptr< UanChannel > chan) private
Create node function.
Parameters
pos the position of the device
chan the communication channel
Returns
the UAN device
Definition at line 117 of file uan-test.cc.
References ns3::ObjectFactory::Create(), m_phyFac, third::mac, third::mobility, third::phy, ns3::UanNetDevice::SetChannel(), ns3::UanNetDevice::SetMac(), ns3::UanNetDevice::SetPhy(), and ns3::UanNetDevice::SetTransducer().
Referenced by DoOnePhyTest().
DoOnePhyTest()
uint32_t UanTest::DoOnePhyTest (Time t1, Time t2, uint32_t r1, uint32_t r2, Ptr< UanPropModel > prop, uint16_t mode1 = 0, uint16_t mode2 = 0) private
Do one Phy test function.
Parameters
t1 the time to send first packet
t2 the time to send the second packet
r1 first distance constant
r2 second distance constant
prop the propagation model
mode1 the send mode for device 1
mode2 the send mode for device 2
Returns
number of bytes received
Definition at line 144 of file uan-test.cc.
References channel, CreateNode(), m_bytesRx, ns3::MakeCallback(), RxPacket(), ns3::Seconds(), SendOnePacket(), ns3::ObjectBase::SetAttribute(), and ns3::UanNetDevice::SetReceiveCallback().
Referenced by DoPhyTests().
DoPhyTests()
bool UanTest::DoPhyTests () private
Phy test function.
Returns
true if successful
Definition at line 175 of file uan-test.cc.
References ns3::UanModesList::AppendMode(), DoOnePhyTest(), MRG32k3a::m1, m_phyFac, NS_TEST_ASSERT_MSG_EQ_RETURNS_BOOL, ns3::Seconds(), ns3::ObjectFactory::Set(), and ns3::ObjectFactory::SetTypeId().
Referenced by DoRun().
DoRun()
void UanTest::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 264 of file uan-test.cc.
References ns3::UanPhyPerUmodem::CalcPer(), DoPhyTests(), and NS_TEST_ASSERT_MSG_EQ_TOL.
RxPacket()
bool UanTest::RxPacket (Ptr< NetDevice > dev, Ptr< const Packet > pkt, uint16_t mode, const Address & sender) private
Receive packet function.
Parameters
dev the device
pkt the packet
mode the receive mode
sender the address of the sender
Returns
true if successful
Definition at line 101 of file uan-test.cc.
References ns3::Packet::GetSize(), m_bytesRx, and NS_UNUSED.
Referenced by DoOnePhyTest().
SendOnePacket()
void UanTest::SendOnePacket (Ptr< UanNetDevice > dev, uint16_t mode) private
Send one packet function.
Parameters
dev the device
mode the transmit mode
Definition at line 109 of file uan-test.cc.
References ns3::UanNetDevice::GetBroadcast(), ns3::UanNetDevice::Send(), and ns3::UanNetDevice::SetTxModeIndex().
Referenced by DoOnePhyTest().
Member Data Documentation
m_bytesRx
uint32_t UanTest::m_bytesRx private
byes received
Definition at line 90 of file uan-test.cc.
Referenced by DoOnePhyTest(), and RxPacket().
m_phyFac
ObjectFactory UanTest::m_phyFac private
Phy.
Definition at line 89 of file uan-test.cc.
Referenced by CreateNode(), and DoPhyTests().
The documentation for this class was generated from the following file:
src/uan/test/uan-test.cc