ns-3: ns3::ConstantWifiAckPolicySelector Class Reference
ns3::ConstantWifiAckPolicySelector Class Reference
Wifi Models
#include "constant-wifi-ack-policy-selector.h"
Public Member Functions
ConstantWifiAckPolicySelector ()
virtual ~ConstantWifiAckPolicySelector ()
virtual void UpdateTxParams (Ptr< WifiPsdu > psdu, MacLowTransmissionParameters &params)
Update the transmission parameters related to the acknowledgment policy for the given PSDU.
Public Member Functions inherited from ns3::WifiAckPolicySelector
virtual ~WifiAckPolicySelector ()
virtual void DoDispose (void)
Destructor implementation.
Ptr< QosTxop > GetQosTxop (void) const
Get the QoS Txop associated with this ack policy selector.
void SetQosTxop (Ptr< QosTxop > qosTxop)
Set the QoS Txop associated with this ack policy selector.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::WifiAckPolicySelector
static TypeId GetTypeId (void)
Get the type ID.
static void SetAckPolicy (Ptr< WifiPsdu > psdu, const MacLowTransmissionParameters &params)
Set the QoS Ack Policy for the QoS Data frames contained in the given PSDU according to the given MacLow transmission parameters.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
double m_baThreshold
Threshold to determine when a Block Ack must be requested.
bool m_useExplicitBar
true for sending BARs, false for using Implicit BAR Ack policy
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::WifiAckPolicySelector
Ptr< QosTxop > m_qosTxop
the QoS Txop this selector is associated with
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
A constant ack policy selector operating based on the values of its attributes.
Definition at line 33 of file constant-wifi-ack-policy-selector.h.
Constructor & Destructor Documentation
ConstantWifiAckPolicySelector()
ns3::ConstantWifiAckPolicySelector::ConstantWifiAckPolicySelector ()
Definition at line 56 of file constant-wifi-ack-policy-selector.cc.
References NS_LOG_FUNCTION_NOARGS.
~ConstantWifiAckPolicySelector()
ns3::ConstantWifiAckPolicySelector::~ConstantWifiAckPolicySelector () virtual
Definition at line 61 of file constant-wifi-ack-policy-selector.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
GetTypeId()
TypeId ns3::ConstantWifiAckPolicySelector::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 31 of file constant-wifi-ack-policy-selector.cc.
References m_baThreshold, m_useExplicitBar, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeDoubleAccessor(), and ns3::TypeId::SetParent().
UpdateTxParams()
void ns3::ConstantWifiAckPolicySelector::UpdateTxParams (Ptr< WifiPsdu > psdu, MacLowTransmissionParameters & params) virtual
Update the transmission parameters related to the acknowledgment policy for the given PSDU.
This method is typically called by the MPDU aggregator when trying to aggregate another MPDU to the current A-MPDU. In fact, the AckPolicySelector may switch to a different acknowledgment policy when a new MPDU is aggregated to an A-MPDU. Note that multi-TID A-MPDUs are currently not supported by this method.
Parameters
psdu the given PSDU.
params the MacLow parameters to update.
Implements ns3::WifiAckPolicySelector.
Definition at line 67 of file constant-wifi-ack-policy-selector.cc.
References ns3::COMPRESSED_BLOCK_ACK, ns3::MacLowTransmissionParameters::DisableAck(), ns3::MacLowTransmissionParameters::EnableAck(), ns3::MacLowTransmissionParameters::EnableBlockAck(), ns3::MacLowTransmissionParameters::EnableBlockAckRequest(), ns3::EXTENDED_COMPRESSED_BLOCK_ACK, ns3::QosTxop::GetBaAgreementEstablished(), ns3::QosTxop::GetBaBufferSize(), ns3::QosTxop::GetBaStartingSequence(), ns3::Txop::GetTxopLimit(), ns3::QosTxop::GetTxopRemaining(), ns3::Time::IsStrictlyPositive(), m_baThreshold, ns3::WifiAckPolicySelector::m_qosTxop, m_useExplicitBar, ns3::MacLowTransmissionParameters::MustSendBlockAckRequest(), ns3::MacLowTransmissionParameters::MustSendRts(), NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, and ns3::QosTxop::PeekNextFrame().
Member Data Documentation
m_baThreshold
double ns3::ConstantWifiAckPolicySelector::m_baThreshold private
Threshold to determine when a Block Ack must be requested.
Definition at line 60 of file constant-wifi-ack-policy-selector.h.
Referenced by GetTypeId(), and UpdateTxParams().
m_useExplicitBar
bool ns3::ConstantWifiAckPolicySelector::m_useExplicitBar private
true for sending BARs, false for using Implicit BAR Ack policy
Definition at line 59 of file constant-wifi-ack-policy-selector.h.
Referenced by GetTypeId(), and UpdateTxParams().
The documentation for this class was generated from the following files:
src/wifi/model/constant-wifi-ack-policy-selector.h
src/wifi/model/constant-wifi-ack-policy-selector.cc