ns-3: ns3::ChannelAccessManager Class Reference
ns3::ChannelAccessManager Class Reference
Wifi Models
Manage a set of ns3::Txop.
#include "channel-access-manager.h"
Public Member Functions
ChannelAccessManager ()
virtual ~ChannelAccessManager ()
void Add (Ptr< Txop > dcf)
Time GetEifsNoDifs (void) const
bool IsBusy (void) const
Check if the device is busy sending or receiving, or NAV or CCA busy.
bool NeedBackoffUponAccess (Ptr< Txop > txop)
Determine if a new backoff needs to be generated when a packet is queued for transmission.
void NotifyAckTimeoutResetNow (void)
Notify that ACK timer has reset.
void NotifyAckTimeoutStartNow (Time duration)
Notify that ACK timer has started for the given duration.
void NotifyCtsTimeoutResetNow (void)
Notify that CTS timer has reset.
void NotifyCtsTimeoutStartNow (Time duration)
Notify that CTS timer has started for the given duration.
void NotifyMaybeCcaBusyStartNow (Time duration)
void NotifyNavResetNow (Time duration)
void NotifyNavStartNow (Time duration)
void NotifyOffNow (void)
Notify the DCF that the device has been put in off mode.
void NotifyOnNow (void)
Notify the DCF that the device has been resumed from off mode.
void NotifyRxEndErrorNow (void)
Notify the DCF that a packet reception was just completed unsuccessfully.
void NotifyRxEndOkNow (void)
Notify the DCF that a packet reception was just completed successfully.
void NotifyRxStartNow (Time duration)
void NotifySleepNow (void)
Notify the DCF that the device has been put in sleep mode.
void NotifySwitchingStartNow (Time duration)
void NotifyTxStartNow (Time duration)
void NotifyWakeupNow (void)
Notify the DCF that the device has been resumed from sleep mode.
void RemovePhyListener (Ptr< WifiPhy > phy)
Remove current registered listener for Phy events.
void RequestAccess (Ptr< Txop > state, bool isCfPeriod=false)
void SetEifsNoDifs (Time eifsNoDifs)
void SetSifs (Time sifs)
void SetSlot (Time slotTime)
void SetupLow (Ptr< MacLow > low)
Set up listener for MacLow events.
void SetupPhyListener (Ptr< WifiPhy > phy)
Set up listener for Phy events.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Protected Member Functions
void DoDispose (void)
Destructor implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Types
typedef std::vector< Ptr< Txop > > States
typedef for a vector of Txops
Private Member Functions
void AccessTimeout (void)
Called when access timeout should occur (e.g.
void DoGrantDcfAccess (void)
Grant access to DCF.
void DoGrantPcfAccess (Ptr< Txop > state)
Grant access to PCF.
void DoRestartAccessTimeoutIfNeeded (void)
Time GetAccessGrantStart (bool ignoreNav=false) const
Access will never be granted to the medium before the time returned by this method.
Time GetBackoffEndFor (Ptr< Txop > state)
Return the time when the backoff procedure ended (or will ended) for the given Txop.
Time GetBackoffStartFor (Ptr< Txop > state)
Return the time when the backoff procedure started for the given Txop.
Time MostRecent (std::initializer_list< Time > list) const
Return the most recent time.
void UpdateBackoff (void)
Update backoff slots for all Txops.
Private Attributes
EventId m_accessTimeout
the access timeout ID
Time m_eifsNoDifs
EIFS no DIFS time.
Time m_lastAckTimeoutEnd
the last ACK timeout end time
Time m_lastBusyDuration
the last busy duration time
Time m_lastBusyStart
the last busy start time
Time m_lastCtsTimeoutEnd
the last CTS timeout end time
Time m_lastNavDuration
the last NAV duration time
Time m_lastNavStart
the last NAV start time
Time m_lastRxDuration
the last receive duration time
Time m_lastRxEnd
the last receive end time
bool m_lastRxReceivedOk
the last receive OK
Time m_lastRxStart
the last receive start time
Time m_lastSwitchingDuration
the last switching duration time
Time m_lastSwitchingStart
the last switching start time
Time m_lastTxDuration
the last transmit duration time
Time m_lastTxStart
the last transmit start time
bool m_off
flag whether it is in off state
Ptr< WifiPhy > m_phy
Ptr to the PHY.
PhyListener * m_phyListener
the phy listener
Time m_sifs
the SIFS time
bool m_sleeping
flag whether it is in sleeping state
Time m_slot
the slot time
States m_states
the DCF states
Additional Inherited Members
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Manage a set of ns3::Txop.
Handle a set of independent ns3::Txop, each of which represents a single DCF within a MAC stack. Each ns3::Txop has a priority implicitly associated with it (the priority is determined when the ns3::Txop is added to the ChannelAccessManager: the first Txop to be added gets the highest priority, the second, the second highest priority, and so on.) which is used to handle "internal" collisions. i.e., when two local Txop are expected to get access to the medium at the same time, the highest priority local Txop wins access to the medium and the other Txop suffers a "internal" collision.
Definition at line 51 of file channel-access-manager.h.
Member Typedef Documentation
States
typedef std::vector<Ptr<Txop> > ns3::ChannelAccessManager::States private
typedef for a vector of Txops
Definition at line 300 of file channel-access-manager.h.
Constructor & Destructor Documentation
ChannelAccessManager()
ns3::ChannelAccessManager::ChannelAccessManager ()
Definition at line 101 of file channel-access-manager.cc.
References NS_LOG_FUNCTION.
~ChannelAccessManager()
ns3::ChannelAccessManager::~ChannelAccessManager () virtual
Definition at line 125 of file channel-access-manager.cc.
References m_phyListener, and NS_LOG_FUNCTION.
Member Function Documentation
AccessTimeout()
void ns3::ChannelAccessManager::AccessTimeout (void) private
Called when access timeout should occur (e.g.
backoff procedure expired).
Definition at line 399 of file channel-access-manager.cc.
References DoGrantDcfAccess(), DoRestartAccessTimeoutIfNeeded(), NS_LOG_FUNCTION, and UpdateBackoff().
Referenced by DoRestartAccessTimeoutIfNeeded().
Add()
void ns3::ChannelAccessManager::Add (Ptr< Txop > dcf)
Parameters
dcf a new Txop.
The ChannelAccessManager does not take ownership of this pointer so, the callee must make sure that the Txop pointer will stay valid as long as the ChannelAccessManager is valid. Note that the order in which Txop objects are added to a ChannelAccessManager matters: the first Txop added has the highest priority, the second Txop added, has the second highest priority, etc.
Definition at line 203 of file channel-access-manager.cc.
References m_states, and NS_LOG_FUNCTION.
Referenced by ns3::Txop::SetChannelAccessManager().
DoDispose()
void ns3::ChannelAccessManager::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 133 of file channel-access-manager.cc.
References m_phy, m_states, and NS_LOG_FUNCTION.
DoGrantDcfAccess()
void ns3::ChannelAccessManager::DoGrantDcfAccess (void) private
Grant access to DCF.
This is the first dcf we find with an expired backoff and which needs access to the medium. i.e., it has data to send.
all other dcfs with a lower priority whose backoff has expired and which needed access to the medium must be notified that we did get an internal collision.
Now, we notify all of these changes in one go. It is necessary to perform first the calculations of which states are colliding and then only apply the changes because applying the changes through notification could change the global state of the manager, and, thus, could change the result of the calculations.
Definition at line 344 of file channel-access-manager.cc.
References GetBackoffEndFor(), ns3::Txop::GetBackoffSlots(), ns3::Txop::IsAccessRequested(), m_states, ns3::Txop::NotifyAccessGranted(), ns3::Simulator::Now(), NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by AccessTimeout(), and RequestAccess().
DoGrantPcfAccess()
void ns3::ChannelAccessManager::DoGrantPcfAccess (Ptr< Txop > state) private
Grant access to PCF.
Parameters
state
Definition at line 338 of file channel-access-manager.cc.
References ns3::Txop::NotifyAccessGranted().
Referenced by RequestAccess().
DoRestartAccessTimeoutIfNeeded()
void ns3::ChannelAccessManager::DoRestartAccessTimeoutIfNeeded (void) private
Is there a Txop which needs to access the medium, and, if there is one, how many slots for AIFS+backoff does it require ?
Definition at line 518 of file channel-access-manager.cc.
References AccessTimeout(), ns3::EventId::Cancel(), GetBackoffEndFor(), ns3::Simulator::GetDelayLeft(), ns3::Simulator::GetMaximumSimulationTime(), ns3::Txop::IsAccessRequested(), ns3::EventId::IsExpired(), ns3::EventId::IsRunning(), m_accessTimeout, m_states, min, ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, and ns3::Simulator::Schedule().
Referenced by AccessTimeout(), NotifyAckTimeoutResetNow(), NotifyCtsTimeoutResetNow(), NotifyNavResetNow(), and RequestAccess().
GetAccessGrantStart()
Time ns3::ChannelAccessManager::GetAccessGrantStart (bool ignoreNav = false) const private
Access will never be granted to the medium before the time returned by this method.
Parameters
ignoreNav flag whether NAV should be ignored
Returns
the absolute time at which access could start to be granted
Definition at line 408 of file channel-access-manager.cc.
References m_eifsNoDifs, m_lastAckTimeoutEnd, m_lastBusyDuration, m_lastBusyStart, m_lastCtsTimeoutEnd, m_lastNavDuration, m_lastNavStart, m_lastRxDuration, m_lastRxEnd, m_lastRxReceivedOk, m_lastRxStart, m_lastSwitchingDuration, m_lastSwitchingStart, m_lastTxDuration, m_lastTxStart, m_sifs, MostRecent(), ns3::Simulator::Now(), NS_LOG_FUNCTION, and NS_LOG_INFO.
Referenced by GetBackoffStartFor(), and RequestAccess().
GetBackoffEndFor()
Time ns3::ChannelAccessManager::GetBackoffEndFor (Ptr< Txop > state) private
Return the time when the backoff procedure ended (or will ended) for the given Txop.
Parameters
state
Returns
the time when the backoff procedure ended (or will ended)
Definition at line 472 of file channel-access-manager.cc.
References ns3::Time::As(), ns3::Txop::GetBackoffSlots(), GetBackoffStartFor(), m_slot, NS_LOG_DEBUG, NS_LOG_FUNCTION, and ns3::Time::US.
Referenced by DoGrantDcfAccess(), and DoRestartAccessTimeoutIfNeeded().
GetBackoffStartFor()
Time ns3::ChannelAccessManager::GetBackoffStartFor (Ptr< Txop > state) private
Return the time when the backoff procedure started for the given Txop.
Parameters
state
Returns
the time when the backoff procedure started
Definition at line 461 of file channel-access-manager.cc.
References ns3::Time::As(), GetAccessGrantStart(), ns3::Txop::GetAifsn(), ns3::Txop::GetBackoffStart(), m_slot, MostRecent(), NS_LOG_DEBUG, NS_LOG_FUNCTION, and ns3::Time::US.
Referenced by GetBackoffEndFor(), and UpdateBackoff().
GetEifsNoDifs()
Time ns3::ChannelAccessManager::GetEifsNoDifs (void) const
Returns
value set previously using SetEifsNoDifs.
Definition at line 196 of file channel-access-manager.cc.
References m_eifsNoDifs, and NS_LOG_FUNCTION.
Referenced by ns3::RegularWifiMac::GetEifsNoDifs().
IsBusy()
bool ns3::ChannelAccessManager::IsBusy (void) const
Check if the device is busy sending or receiving, or NAV or CCA busy.
Returns
true if the device is busy, false otherwise
Definition at line 217 of file channel-access-manager.cc.
References m_lastBusyDuration, m_lastBusyStart, m_lastNavDuration, m_lastNavStart, m_lastRxEnd, m_lastTxDuration, m_lastTxStart, ns3::Simulator::Now(), and NS_LOG_FUNCTION.
Referenced by ns3::Txop::CanStartNextPolling(), and NeedBackoffUponAccess().
MostRecent()
Time ns3::ChannelAccessManager::MostRecent (std::initializer_list< Time > list) const private
Return the most recent time.
Parameters
list the initializer list including the times to compare
Returns
the most recent time
Definition at line 210 of file channel-access-manager.cc.
References list, and NS_ASSERT.
Referenced by GetAccessGrantStart(), GetBackoffStartFor(), and RequestAccess().
NeedBackoffUponAccess()
bool ns3::ChannelAccessManager::NeedBackoffUponAccess (Ptr< Txop > txop)
Determine if a new backoff needs to be generated when a packet is queued for transmission.
Parameters
txop the Txop requesting to generate a backoff
Returns
true if backoff needs to be generated, false otherwise
Definition at line 246 of file channel-access-manager.cc.
References ns3::Txop::GetAifsn(), ns3::Txop::GetBackoffSlots(), ns3::Txop::GetLow(), ns3::Txop::HasFramesToTransmit(), IsBusy(), ns3::Txop::IsQosTxop(), m_sifs, m_slot, ns3::Simulator::Now(), NS_LOG_FUNCTION, ns3::Seconds(), UpdateBackoff(), and ns3::Txop::UpdateBackoffSlotsNow().
Referenced by ns3::Txop::Queue().
NotifyAckTimeoutResetNow()
void ns3::ChannelAccessManager::NotifyAckTimeoutResetNow (void)
Notify that ACK timer has reset.
Definition at line 802 of file channel-access-manager.cc.
References DoRestartAccessTimeoutIfNeeded(), m_lastAckTimeoutEnd, ns3::Simulator::Now(), and NS_LOG_FUNCTION.
NotifyAckTimeoutStartNow()
void ns3::ChannelAccessManager::NotifyAckTimeoutStartNow (Time duration)
Notify that ACK timer has started for the given duration.
Parameters
duration
Definition at line 794 of file channel-access-manager.cc.
References m_lastAckTimeoutEnd, ns3::Simulator::Now(), NS_ASSERT, and NS_LOG_FUNCTION.
NotifyCtsTimeoutResetNow()
void ns3::ChannelAccessManager::NotifyCtsTimeoutResetNow (void)
Notify that CTS timer has reset.
Definition at line 817 of file channel-access-manager.cc.
References DoRestartAccessTimeoutIfNeeded(), m_lastCtsTimeoutEnd, ns3::Simulator::Now(), and NS_LOG_FUNCTION.
NotifyCtsTimeoutStartNow()
void ns3::ChannelAccessManager::NotifyCtsTimeoutStartNow (Time duration)
Notify that CTS timer has started for the given duration.
Parameters
duration
Definition at line 810 of file channel-access-manager.cc.
References m_lastCtsTimeoutEnd, ns3::Simulator::Now(), and NS_LOG_FUNCTION.
NotifyMaybeCcaBusyStartNow()
void ns3::ChannelAccessManager::NotifyMaybeCcaBusyStartNow (Time duration)
Parameters
duration expected duration of cca busy period
Notify the DCF that a CCA busy period has just started.
Definition at line 614 of file channel-access-manager.cc.
References m_lastBusyDuration, m_lastBusyStart, ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, and UpdateBackoff().
Referenced by ns3::OcbWifiMac::MakeVirtualBusy(), and ns3::PhyListener::NotifyMaybeCcaBusyStart().
NotifyNavResetNow()
void ns3::ChannelAccessManager::NotifyNavResetNow (Time duration)
Parameters
duration the value of the received NAV.
Called at end of rx
If the nav reset indicates an end-of-nav which is earlier than the previous end-of-nav, the expected end of backoff might be later than previously thought so, we might need to restart a new access timeout.
Definition at line 761 of file channel-access-manager.cc.
References DoRestartAccessTimeoutIfNeeded(), m_lastNavDuration, m_lastNavStart, ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, and UpdateBackoff().
Referenced by ns3::MeshWifiInterfaceMac::SwitchFrequencyChannel().
NotifyNavStartNow()
void ns3::ChannelAccessManager::NotifyNavStartNow (Time duration)
Parameters
duration the value of the received NAV.
Called at end of rx
Definition at line 778 of file channel-access-manager.cc.
References m_lastNavDuration, m_lastNavStart, ns3::Simulator::Now(), NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, and UpdateBackoff().
NotifyOffNow()
void ns3::ChannelAccessManager::NotifyOffNow (void)
Notify the DCF that the device has been put in off mode.
Definition at line 702 of file channel-access-manager.cc.
References ns3::EventId::Cancel(), ns3::EventId::IsRunning(), m_accessTimeout, m_off, m_states, ns3::Txop::NotifyOff(), and NS_LOG_FUNCTION.
Referenced by ns3::PhyListener::NotifyOff().
NotifyOnNow()
void ns3::ChannelAccessManager::NotifyOnNow (void)
Notify the DCF that the device has been resumed from off mode.
Definition at line 741 of file channel-access-manager.cc.
References ns3::Txop::GetBackoffSlots(), ns3::Txop::m_accessRequested, m_off, m_states, ns3::Txop::NotifyOn(), ns3::Simulator::Now(), NS_ASSERT, NS_LOG_FUNCTION, ns3::Txop::ResetCw(), and ns3::Txop::UpdateBackoffSlotsNow().
Referenced by ns3::PhyListener::NotifyOn().
NotifyRxEndErrorNow()
void ns3::ChannelAccessManager::NotifyRxEndErrorNow (void)
Notify the DCF that a packet reception was just completed unsuccessfully.
Definition at line 580 of file channel-access-manager.cc.
References m_lastBusyDuration, m_lastBusyStart, m_lastRxDuration, m_lastRxEnd, m_lastRxReceivedOk, m_lastRxStart, ns3::Simulator::Now(), NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by ns3::PhyListener::NotifyRxEndError().
NotifyRxEndOkNow()
void ns3::ChannelAccessManager::NotifyRxEndOkNow (void)
Notify the DCF that a packet reception was just completed successfully.
Definition at line 570 of file channel-access-manager.cc.
References m_lastRxDuration, m_lastRxEnd, m_lastRxReceivedOk, m_lastRxStart, ns3::Simulator::Now(), NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by ns3::PhyListener::NotifyRxEndOk().
NotifyRxStartNow()
void ns3::ChannelAccessManager::NotifyRxStartNow (Time duration)
Parameters
duration expected duration of reception
Notify the DCF that a packet reception started for the expected duration.
Definition at line 559 of file channel-access-manager.cc.
References m_lastRxDuration, m_lastRxEnd, m_lastRxStart, ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, and UpdateBackoff().
Referenced by ns3::PhyListener::NotifyRxStart().
NotifySleepNow()
void ns3::ChannelAccessManager::NotifySleepNow (void)
Notify the DCF that the device has been put in sleep mode.
Definition at line 683 of file channel-access-manager.cc.
References ns3::EventId::Cancel(), ns3::EventId::IsRunning(), m_accessTimeout, m_sleeping, m_states, ns3::Txop::NotifySleep(), and NS_LOG_FUNCTION.
Referenced by ns3::PhyListener::NotifySleep(), and ns3::OcbWifiMac::Suspend().
NotifySwitchingStartNow()
void ns3::ChannelAccessManager::NotifySwitchingStartNow (Time duration)
Parameters
duration expected duration of channel switching period
Notify the DCF that a channel switching period has just started. During switching state, new packets can be enqueued in Txop/QosTxop but they won't access to the medium until the end of the channel switching.
Definition at line 624 of file channel-access-manager.cc.
References ns3::EventId::Cancel(), ns3::Txop::GetBackoffSlots(), ns3::EventId::IsRunning(), ns3::Txop::m_accessRequested, m_accessTimeout, m_lastAckTimeoutEnd, m_lastBusyDuration, m_lastBusyStart, m_lastCtsTimeoutEnd, m_lastNavDuration, m_lastNavStart, m_lastRxDuration, m_lastRxEnd, m_lastRxReceivedOk, m_lastRxStart, m_lastSwitchingDuration, m_lastSwitchingStart, m_lastTxDuration, m_lastTxStart, m_states, ns3::Txop::NotifyChannelSwitching(), ns3::Simulator::Now(), NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::Txop::ResetCw(), and ns3::Txop::UpdateBackoffSlotsNow().
Referenced by ns3::PhyListener::NotifySwitchingStart(), and ns3::OcbWifiMac::Reset().
NotifyTxStartNow()
void ns3::ChannelAccessManager::NotifyTxStartNow (Time duration)
Parameters
duration expected duration of transmission
Notify the DCF that a packet transmission was just started and is expected to last for the specified duration.
Definition at line 595 of file channel-access-manager.cc.
References m_lastRxDuration, m_lastRxEnd, m_lastRxReceivedOk, m_lastRxStart, m_lastTxDuration, m_lastTxStart, m_sifs, ns3::Simulator::Now(), NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, and UpdateBackoff().
Referenced by ns3::PhyListener::NotifyTxStart().
NotifyWakeupNow()
void ns3::ChannelAccessManager::NotifyWakeupNow (void)
Notify the DCF that the device has been resumed from sleep mode.
Definition at line 721 of file channel-access-manager.cc.
References ns3::Txop::GetBackoffSlots(), ns3::Txop::m_accessRequested, m_sleeping, m_states, ns3::Txop::NotifyWakeUp(), ns3::Simulator::Now(), NS_ASSERT, NS_LOG_FUNCTION, ns3::Txop::ResetCw(), and ns3::Txop::UpdateBackoffSlotsNow().
Referenced by ns3::PhyListener::NotifyWakeup(), and ns3::OcbWifiMac::Resume().
RemovePhyListener()
void ns3::ChannelAccessManager::RemovePhyListener (Ptr< WifiPhy > phy)
Remove current registered listener for Phy events.
Parameters
phy
Definition at line 155 of file channel-access-manager.cc.
References m_phy, m_phyListener, NS_LOG_FUNCTION, and third::phy.
Referenced by ns3::RegularWifiMac::ResetWifiPhy().
RequestAccess()
void ns3::ChannelAccessManager::RequestAccess (Ptr< Txop > state, bool isCfPeriod = false)
Parameters
state a Txop
isCfPeriod flag whether it is called during the CF period
Notify the ChannelAccessManager that a specific Txop needs access to the medium. The ChannelAccessManager is then responsible for starting an access timer and, invoking Txop::DoNotifyAccessGranted when the access is granted if it ever gets granted.
Definition at line 296 of file channel-access-manager.cc.
References DoGrantDcfAccess(), DoGrantPcfAccess(), DoRestartAccessTimeoutIfNeeded(), GetAccessGrantStart(), ns3::Txop::GetAifsn(), ns3::Txop::GetBackoffStart(), ns3::Txop::IsAccessRequested(), ns3::Txop::IsQosTxop(), m_accessTimeout, m_off, m_phy, m_sleeping, m_slot, MostRecent(), ns3::Txop::NotifyAccessRequested(), ns3::WifiPhy::NotifyChannelAccessRequested(), ns3::Simulator::Now(), NS_ASSERT, NS_LOG_FUNCTION, ns3::Simulator::Schedule(), UpdateBackoff(), and ns3::Txop::UpdateBackoffSlotsNow().
Referenced by ns3::QosTxop::RestartAccessIfNeeded(), ns3::Txop::RestartAccessIfNeeded(), ns3::Txop::SendCfFrame(), ns3::QosTxop::StartAccessIfNeeded(), and ns3::Txop::StartAccessIfNeeded().
SetEifsNoDifs()
void ns3::ChannelAccessManager::SetEifsNoDifs (Time eifsNoDifs)
Parameters
eifsNoDifs the duration of a EIFS minus the duration of DIFS.
It is a bad idea to call this method after RequestAccess or one of the Notify methods has been invoked.
Definition at line 189 of file channel-access-manager.cc.
References m_eifsNoDifs, and NS_LOG_FUNCTION.
Referenced by ns3::RegularWifiMac::SetEifsNoDifs().
SetSifs()
void ns3::ChannelAccessManager::SetSifs (Time sifs)
Parameters
sifs the duration of a SIFS.
It is a bad idea to call this method after RequestAccess or one of the Notify methods has been invoked.
Definition at line 182 of file channel-access-manager.cc.
References m_sifs, and NS_LOG_FUNCTION.
Referenced by ns3::RegularWifiMac::SetSifs().
SetSlot()
void ns3::ChannelAccessManager::SetSlot (Time slotTime)
Parameters
slotTime the duration of a slot.
It is a bad idea to call this method after RequestAccess or one of the Notify methods has been invoked.
Definition at line 175 of file channel-access-manager.cc.
References m_slot, and NS_LOG_FUNCTION.
Referenced by ns3::RegularWifiMac::SetSlot().
SetupLow()
void ns3::ChannelAccessManager::SetupLow (Ptr< MacLow > low)
Set up listener for MacLow events.
Parameters
low
Definition at line 168 of file channel-access-manager.cc.
References NS_LOG_FUNCTION.
Referenced by ns3::RegularWifiMac::RegularWifiMac(), and ns3::OcbWifiMac::EnableForWave().
SetupPhyListener()
void ns3::ChannelAccessManager::SetupPhyListener (Ptr< WifiPhy > phy)
Set up listener for Phy events.
Parameters
phy
Definition at line 145 of file channel-access-manager.cc.
References m_phy, m_phyListener, NS_ASSERT, NS_LOG_FUNCTION, and third::phy.
Referenced by ns3::RegularWifiMac::SetWifiPhy().
UpdateBackoff()
void ns3::ChannelAccessManager::UpdateBackoff (void) private
Update backoff slots for all Txops.
Definition at line 482 of file channel-access-manager.cc.
References ns3::Txop::GetBackoffSlots(), GetBackoffStartFor(), ns3::Txop::IsQosTxop(), m_slot, m_states, min, sample-rng-plot::n, ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, and ns3::Txop::UpdateBackoffSlotsNow().
Referenced by AccessTimeout(), NeedBackoffUponAccess(), NotifyMaybeCcaBusyStartNow(), NotifyNavResetNow(), NotifyNavStartNow(), NotifyRxStartNow(), NotifyTxStartNow(), and RequestAccess().
Member Data Documentation
m_accessTimeout
EventId ns3::ChannelAccessManager::m_accessTimeout private
the access timeout ID
Definition at line 320 of file channel-access-manager.h.
Referenced by DoRestartAccessTimeoutIfNeeded(), NotifyOffNow(), NotifySleepNow(), NotifySwitchingStartNow(), and RequestAccess().
m_eifsNoDifs
Time ns3::ChannelAccessManager::m_eifsNoDifs private
EIFS no DIFS time.
Definition at line 319 of file channel-access-manager.h.
Referenced by GetAccessGrantStart(), GetEifsNoDifs(), and SetEifsNoDifs().
m_lastAckTimeoutEnd
Time ns3::ChannelAccessManager::m_lastAckTimeoutEnd private
the last ACK timeout end time
Definition at line 303 of file channel-access-manager.h.
Referenced by GetAccessGrantStart(), NotifyAckTimeoutResetNow(), NotifyAckTimeoutStartNow(), and NotifySwitchingStartNow().
m_lastBusyDuration
Time ns3::ChannelAccessManager::m_lastBusyDuration private
the last busy duration time
Definition at line 314 of file channel-access-manager.h.
Referenced by GetAccessGrantStart(), IsBusy(), NotifyMaybeCcaBusyStartNow(), NotifyRxEndErrorNow(), and NotifySwitchingStartNow().
m_lastBusyStart
Time ns3::ChannelAccessManager::m_lastBusyStart private
the last busy start time
Definition at line 313 of file channel-access-manager.h.
Referenced by GetAccessGrantStart(), IsBusy(), NotifyMaybeCcaBusyStartNow(), NotifyRxEndErrorNow(), and NotifySwitchingStartNow().
m_lastCtsTimeoutEnd
Time ns3::ChannelAccessManager::m_lastCtsTimeoutEnd private
the last CTS timeout end time
Definition at line 304 of file channel-access-manager.h.
Referenced by GetAccessGrantStart(), NotifyCtsTimeoutResetNow(), NotifyCtsTimeoutStartNow(), and NotifySwitchingStartNow().
m_lastNavDuration
Time ns3::ChannelAccessManager::m_lastNavDuration private
the last NAV duration time
Definition at line 306 of file channel-access-manager.h.
Referenced by GetAccessGrantStart(), IsBusy(), NotifyNavResetNow(), NotifyNavStartNow(), and NotifySwitchingStartNow().
m_lastNavStart
Time ns3::ChannelAccessManager::m_lastNavStart private
the last NAV start time
Definition at line 305 of file channel-access-manager.h.
Referenced by GetAccessGrantStart(), IsBusy(), NotifyNavResetNow(), NotifyNavStartNow(), and NotifySwitchingStartNow().
m_lastRxDuration
Time ns3::ChannelAccessManager::m_lastRxDuration private
the last receive duration time
Definition at line 308 of file channel-access-manager.h.
Referenced by GetAccessGrantStart(), NotifyRxEndErrorNow(), NotifyRxEndOkNow(), NotifyRxStartNow(), NotifySwitchingStartNow(), and NotifyTxStartNow().
m_lastRxEnd
Time ns3::ChannelAccessManager::m_lastRxEnd private
the last receive end time
Definition at line 310 of file channel-access-manager.h.
Referenced by GetAccessGrantStart(), IsBusy(), NotifyRxEndErrorNow(), NotifyRxEndOkNow(), NotifyRxStartNow(), NotifySwitchingStartNow(), and NotifyTxStartNow().
m_lastRxReceivedOk
bool ns3::ChannelAccessManager::m_lastRxReceivedOk private
the last receive OK
Definition at line 309 of file channel-access-manager.h.
Referenced by GetAccessGrantStart(), NotifyRxEndErrorNow(), NotifyRxEndOkNow(), NotifySwitchingStartNow(), and NotifyTxStartNow().
m_lastRxStart
Time ns3::ChannelAccessManager::m_lastRxStart private
the last receive start time
Definition at line 307 of file channel-access-manager.h.
Referenced by GetAccessGrantStart(), NotifyRxEndErrorNow(), NotifyRxEndOkNow(), NotifyRxStartNow(), NotifySwitchingStartNow(), and NotifyTxStartNow().
m_lastSwitchingDuration
Time ns3::ChannelAccessManager::m_lastSwitchingDuration private
the last switching duration time
Definition at line 316 of file channel-access-manager.h.
Referenced by GetAccessGrantStart(), and NotifySwitchingStartNow().
m_lastSwitchingStart
Time ns3::ChannelAccessManager::m_lastSwitchingStart private
the last switching start time
Definition at line 315 of file channel-access-manager.h.
Referenced by GetAccessGrantStart(), and NotifySwitchingStartNow().
m_lastTxDuration
Time ns3::ChannelAccessManager::m_lastTxDuration private
the last transmit duration time
Definition at line 312 of file channel-access-manager.h.
Referenced by GetAccessGrantStart(), IsBusy(), NotifySwitchingStartNow(), and NotifyTxStartNow().
m_lastTxStart
Time ns3::ChannelAccessManager::m_lastTxStart private
the last transmit start time
Definition at line 311 of file channel-access-manager.h.
Referenced by GetAccessGrantStart(), IsBusy(), NotifySwitchingStartNow(), and NotifyTxStartNow().
m_off
bool ns3::ChannelAccessManager::m_off private
flag whether it is in off state
Definition at line 318 of file channel-access-manager.h.
Referenced by NotifyOffNow(), NotifyOnNow(), and RequestAccess().
m_phy
Ptr<WifiPhy> ns3::ChannelAccessManager::m_phy private
Ptr to the PHY.
Definition at line 324 of file channel-access-manager.h.
Referenced by DoDispose(), RemovePhyListener(), RequestAccess(), and SetupPhyListener().
m_phyListener
PhyListener* ns3::ChannelAccessManager::m_phyListener private
the phy listener
Definition at line 323 of file channel-access-manager.h.
Referenced by ~ChannelAccessManager(), RemovePhyListener(), and SetupPhyListener().
m_sifs
Time ns3::ChannelAccessManager::m_sifs private
the SIFS time
Definition at line 322 of file channel-access-manager.h.
Referenced by GetAccessGrantStart(), NeedBackoffUponAccess(), NotifyTxStartNow(), and SetSifs().
m_sleeping
bool ns3::ChannelAccessManager::m_sleeping private
flag whether it is in sleeping state
Definition at line 317 of file channel-access-manager.h.
Referenced by NotifySleepNow(), NotifyWakeupNow(), and RequestAccess().
m_slot
Time ns3::ChannelAccessManager::m_slot private
the slot time
Definition at line 321 of file channel-access-manager.h.
Referenced by GetBackoffEndFor(), GetBackoffStartFor(), NeedBackoffUponAccess(), RequestAccess(), SetSlot(), and UpdateBackoff().
m_states
States ns3::ChannelAccessManager::m_states private
the DCF states
Definition at line 302 of file channel-access-manager.h.
Referenced by Add(), DoDispose(), DoGrantDcfAccess(), DoRestartAccessTimeoutIfNeeded(), NotifyOffNow(), NotifyOnNow(), NotifySleepNow(), NotifySwitchingStartNow(), NotifyWakeupNow(), and UpdateBackoff().
The documentation for this class was generated from the following files:
src/wifi/model/channel-access-manager.h
src/wifi/model/channel-access-manager.cc