ns-3: LiIonEnergyTestCase Class Reference
LiIonEnergyTestCase Class Reference
Public Member Functions
LiIonEnergyTestCase ()
~LiIonEnergyTestCase ()
void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Public Attributes
Ptr< Node > m_node
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 32 of file li-ion-energy-source-test.cc.
Constructor & Destructor Documentation
LiIonEnergyTestCase()
LiIonEnergyTestCase::LiIonEnergyTestCase ()
Definition at line 43 of file li-ion-energy-source-test.cc.
~LiIonEnergyTestCase()
LiIonEnergyTestCase::~LiIonEnergyTestCase ()
Definition at line 48 of file li-ion-energy-source-test.cc.
References m_node.
Member Function Documentation
DoRun()
void LiIonEnergyTestCase::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 54 of file li-ion-energy-source-test.cc.
References ns3::Object::AggregateObject(), ns3::EnergySource::AppendDeviceEnergyModel(), ns3::LiIonEnergySource::GetSupplyVoltage(), m_node, ns3::Now(), NS_TEST_ASSERT_MSG_EQ_TOL, ns3::Seconds(), ns3::SimpleDeviceEnergyModel::SetCurrentA(), ns3::SimpleDeviceEnergyModel::SetEnergySource(), and ns3::EnergySource::SetNode().
Member Data Documentation
m_node
Ptr<Node> LiIonEnergyTestCase::m_node
Definition at line 40 of file li-ion-energy-source-test.cc.
Referenced by ~LiIonEnergyTestCase(), and DoRun().
The documentation for this class was generated from the following file:
src/energy/test/li-ion-energy-source-test.cc